// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef floccalc_h
#define floccalc_h
#include <FL/Fl.H>
int fexist( const char *a_option );
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win3;
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
Fl_Double_Window* make_window();
int main();
#endif
