// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef floccalc_binary_h
#define floccalc_binary_h
#include <FL/Fl.H>
int fexist( const char *a_option );
int foccalc_runwith( const char *fooapp , const char *foofile  );
int fcoccalc_periodic_select_elt( const char *fooelement );
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win1;
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Input.H>
extern Fl_Input *var_input_floc_elements;
extern Fl_Input *var_input_floc_variable1;
extern Fl_Input *var_input_floc_variable2;
extern Fl_Input *var_input_floc_database;
#include <FL/Fl_File_Browser.H>
extern Fl_File_Browser *win_macro_flbrowser1;
#include <FL/Fl_Output.H>
extern Fl_Output *win_macro_flbrowser1_output1;
extern Fl_Input *win_macro_flbrowser1_filter;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *var_fcoccalc_web_browser_def_dillo;
extern Fl_Check_Button *var_fcoccalc_bin_calc_add_ref_phase;
extern Fl_Output *statusbar;
Fl_Double_Window* make_window();
int main( int argc, char *argv[] );
#endif
